import { AIAction } from "./ruleEngine";

type Context = {
  projectId: string;
  tasks: any[];
  memory?: any[];
};

type TraceEvent = {
  type: string;
  message: string;
  data?: any;
  timestamp: number;
};

type ActionTrace = {
  action: AIAction;
  agent?: string;
  rulesTriggered?: string[];
  accepted: boolean;
  reason?: string;
};

/**
 * 🧠 AI OBSERVABILITY LAYER
 * provides full transparency of AI decision-making
 */
export class AIObservabilityLayer {
  private static traces: Map<string, TraceEvent[]> = new Map();

  /**
   * 🟢 LOG SYSTEM EVENT
   */
  static log(projectId: string, event: TraceEvent) {
    const existing = this.traces.get(projectId) || [];

    this.traces.set(projectId, [...existing, event]);
  }

  /**
   * 🧠 TRACE ACTION FLOW
   */
  static traceAction(
    projectId: string,
    actionTrace: ActionTrace
  ) {
    this.log(projectId, {
      type: "action_trace",
      message: `Action ${actionTrace.action.type}`,
      data: actionTrace,
      timestamp: Date.now(),
    });
  }

  /**
   * 📦 GET FULL PROJECT TRACE
   */
  static getTrace(projectId: string) {
    return this.traces.get(projectId) || [];
  }

  /**
   * 🧠 BUILD HUMAN-READABLE EXPLANATION
   */
  static explain(actions: ActionTrace[]) {
    return actions.map((a) => {
      return {
        action: a.action,
        explanation: this.buildExplanation(a),
      };
    });
  }

  /**
   * 🔍 EXPLANATION ENGINE
   */
  private static buildExplanation(trace: ActionTrace): string {
    const { action, agent, accepted, reason } = trace;

    if (!accepted) {
      return `❌ Action "${action.type}" was rejected by rule engine. Reason: ${reason}`;
    }

    return `🟢 Action "${action.type}" was generated by ${agent || "unknown agent"} and approved by system rules.`;
  }

  /**
   * 📊 SYSTEM HEALTH SNAPSHOT
   */
  static getSystemHealth(projectId: string) {
    const logs = this.traces.get(projectId) || [];

    const actions = logs.filter(
      (l) => l.type === "action_trace"
    );

    const rejected = actions.filter((a: any) => !a.data?.accepted);
    const accepted = actions.filter((a: any) => a.data?.accepted);

    return {
      totalEvents: logs.length,
      actionsTotal: actions.length,
      accepted: accepted.length,
      rejected: rejected.length,
      stabilityScore:
        actions.length === 0
          ? 100
          : Math.round(
              (accepted.length / actions.length) * 100
            ),
    };
  }
}